apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: tanzu-system-auth
spec:
  virtualhost:
    fqdn: dex.mgmt.tkg-aws-lab.winterfell.live
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: dexsvc
      port: 5556
