fullName:
  clusterName: se-dpfeffer-wlc-1
  managementClusterName: attached
  name: acme-fitness
  provisionerName: attached
meta:
  labels:
    origin: dpfeffer
spec:
  workspaceName: dpfeffer-acme-fitness-dev
