apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gangway
  namespace: tanzu-system-auth
spec:
  virtualhost:
    fqdn: gangway.wlc-1.tkg-aws-lab.winterfell.live
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: gangwaysvc
      port: 443
